CREATE DATABASE intuitivecare;

USE intuitivecare;

CREATE TABLE Operadoras (
    REGISTRO_OPERADORA VARCHAR(6) NOT NULL PRIMARY KEY,
    CNPJ VARCHAR(14) NOT NULL UNIQUE,
    Razao_Social VARCHAR(140) NOT NULL,
    Nome_Fantasia VARCHAR(140),
    Modalidade VARCHAR(255),
    Logradouro VARCHAR(40),
    Numero VARCHAR(20),
    Complemento VARCHAR(40),
    Bairro VARCHAR(30),
    Cidade VARCHAR(30),
    UF VARCHAR(2),
    CEP VARCHAR(8),
    DDD VARCHAR(4),
    Telefone VARCHAR(20),
    Fax VARCHAR(20),
    Endereco_eletronico VARCHAR(255),
    Representante VARCHAR(50),
    Cargo_Representante VARCHAR(40),
    Regiao_de_Comercializacao VARCHAR(2),
    Data_Registro_ANS DATE
);

CREATE TABLE ContasContabeis (
    DATA DATE NOT NULL,
    REG_ANS VARCHAR(6) NOT NULL,
    CD_CONTA_CONTABIL VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15,2),
    VL_SALDO_FINAL DECIMAL(15,2),
    FOREIGN KEY (REG_ANS) REFERENCES Operadoras(REGISTRO_OPERADORA)
);

LOAD DATA INFILE '/var/lib/mysql-files/Relatorio_cadop.csv'
INTO TABLE Operadoras
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(REGISTRO_OPERADORA, CNPJ, Razao_Social, Nome_Fantasia, Modalidade, Logradouro, Numero, Complemento, Bairro, Cidade, UF, CEP, DDD, Telefone, Fax, Endereco_eletronico, Representante, Cargo_Representante, Regiao_de_Comercializacao, Data_Registro_ANS)
SET Regiao_de_Comercializacao = NULLIF(Regiao_de_Comercializacao, ''),
    Data_Registro_ANS = STR_TO_DATE(Data_Registro_ANS, '%Y-%m-%d');

SET FOREIGN_KEY_CHECKS=0;

LOAD DATA INFILE '/var/lib/mysql-files/csv/1T2023.csv'
INTO TABLE ContasContabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    VL_SALDO_INICIAL = NULLIF(REPLACE(@VL_SALDO_INICIAL, ',', '.'), ''),
    VL_SALDO_FINAL = NULLIF(REPLACE(@VL_SALDO_FINAL, ',', '.'), '');

LOAD DATA INFILE '/var/lib/mysql-files/csv/1T2024.csv'
INTO TABLE ContasContabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    VL_SALDO_INICIAL = NULLIF(REPLACE(@VL_SALDO_INICIAL, ',', '.'), ''),
    VL_SALDO_FINAL = NULLIF(REPLACE(@VL_SALDO_FINAL, ',', '.'), '');

LOAD DATA INFILE '/var/lib/mysql-files/csv/2T2024.csv'
INTO TABLE ContasContabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    VL_SALDO_INICIAL = NULLIF(REPLACE(@VL_SALDO_INICIAL, ',', '.'), ''),
    VL_SALDO_FINAL = NULLIF(REPLACE(@VL_SALDO_FINAL, ',', '.'), '');

LOAD DATA INFILE '/var/lib/mysql-files/csv/2t2023.csv'
INTO TABLE ContasContabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    VL_SALDO_INICIAL = NULLIF(REPLACE(@VL_SALDO_INICIAL, ',', '.'), ''),
    VL_SALDO_FINAL = NULLIF(REPLACE(@VL_SALDO_FINAL, ',', '.'), '');

LOAD DATA INFILE '/var/lib/mysql-files/csv/3T2023.csv'
INTO TABLE ContasContabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    VL_SALDO_INICIAL = NULLIF(REPLACE(@VL_SALDO_INICIAL, ',', '.'), ''),
    VL_SALDO_FINAL = NULLIF(REPLACE(@VL_SALDO_FINAL, ',', '.'), '');

LOAD DATA INFILE '/var/lib/mysql-files/csv/3T2024.csv'
INTO TABLE ContasContabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    VL_SALDO_INICIAL = NULLIF(REPLACE(@VL_SALDO_INICIAL, ',', '.'), ''),
    VL_SALDO_FINAL = NULLIF(REPLACE(@VL_SALDO_FINAL, ',', '.'), '');

LOAD DATA INFILE '/var/lib/mysql-files/csv/4T2023.csv'
INTO TABLE ContasContabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(
        CONCAT(
            SUBSTRING_INDEX(@DATA, '/', -1), '-', 
            LPAD(SUBSTRING_INDEX(SUBSTRING_INDEX(@DATA, '/', 2), '/', -1), 2, '0'), '-',  
            LPAD(SUBSTRING_INDEX(@DATA, '/', 1), 2, '0')  
        ),
        '%Y-%m-%d'
    ),
    VL_SALDO_INICIAL = NULLIF(REPLACE(@VL_SALDO_INICIAL, ',', '.'), ''),
    VL_SALDO_FINAL = NULLIF(REPLACE(@VL_SALDO_FINAL, ',', '.'), '');

LOAD DATA INFILE '/var/lib/mysql-files/csv/4T2024.csv'
INTO TABLE ContasContabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%Y-%m-%d'),
    VL_SALDO_INICIAL = NULLIF(REPLACE(@VL_SALDO_INICIAL, ',', '.'), ''),
    VL_SALDO_FINAL = NULLIF(REPLACE(@VL_SALDO_FINAL, ',', '.'), '');

CREATE INDEX idx_contas_data ON ContasContabeis(DATA);

CREATE INDEX idx_contas_descricao ON ContasContabeis(DESCRICAO);

CREATE INDEX idx_contas_reg_ans ON ContasContabeis(REG_ANS);

CREATE INDEX idx_operadoras_registro ON Operadoras(REGISTRO_OPERADORA);

SELECT 
    o.Razao_Social AS Operadora,
    SUM(c.VL_SALDO_FINAL) AS Total_Despesas
FROM ContasContabeis c
JOIN Operadoras o ON c.REG_ANS = o.REGISTRO_OPERADORA
WHERE TRIM(c.DESCRICAO) LIKE 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS%ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR%'
AND c.DATA BETWEEN '2024-10-01' AND '2024-12-31'
GROUP BY o.Razao_Social
ORDER BY Total_Despesas DESC
LIMIT 10;

SELECT 
    o.Razao_Social AS Operadora,
    SUM(c.VL_SALDO_FINAL) AS Total_Despesas
FROM ContasContabeis c
JOIN Operadoras o ON c.REG_ANS = o.REGISTRO_OPERADORA
WHERE TRIM(c.DESCRICAO) LIKE 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS%ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR%'
AND c.DATA BETWEEN '2023-12-31' AND '2024-12-31'
GROUP BY o.Razao_Social
ORDER BY Total_Despesas DESC
LIMIT 10;